services:
  - type: web
    name: shopfinity
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Shopfinity.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Shopfinity.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
