# Generated by Django 5.1.7 on 2025-04-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phoneNumber',
            new_name='mobNo',
        ),
    ]
