# Generated by Django 5.1.7 on 2025-04-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_rename_phonenumber_contact_mobno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('sub_category', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
