# Generated by Django 5.1.7 on 2025-04-22 05:34

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=django.db.models.fields.AutoField),
        ),
    ]
