# Generated by Django 5.1.7 on 2025-04-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_alter_orders_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amountpaid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='oid',
        ),
    ]
