# Generated by Django 5.1.7 on 2025-04-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_remove_orders_amountpaid_remove_orders_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='oid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
