# Generated by Django 5.1.7 on 2025-04-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_orders_oid_orderupdate_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
