# Generated by Django 5.1.7 on 2025-04-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0010_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderStatus',
            field=models.CharField(default='Not Deliverd', max_length=50),
        ),
    ]
