# Generated by Django 5.1.7 on 2025-04-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0012_alter_orderupdate_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderStatus',
            field=models.CharField(default='Not Delivered', max_length=50),
        ),
    ]
