# Generated by Django 5.1.7 on 2025-04-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0013_alter_orders_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='new_update_desc',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
